# Generated by Django 5.2.16 on 2026-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_collection_reranking_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='source_type',
            field=models.CharField(choices=[('github', 'GitHub Repository'), ('confluence', 'Confluence'), ('json_collection', 'JSON Collection'), ('google_docs', 'Google Docs')], help_text='Type of document source', max_length=20),
        ),
    ]
